# Generated by Django 3.2.6 on 2021-08-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_user_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='login',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
