# Generated by Django 3.2.6 on 2021-08-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_usermodel_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='login',
        ),
    ]
