# Generated by Django 3.2.6 on 2021-08-19 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_usermodel_ip_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='ip_adress',
            new_name='ip_address',
        ),
    ]
