# Generated by Django 3.2.6 on 2021-08-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
